### ISSUE TITLE
Add sonarqube project for each branch (frontend + backend)

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#116]
Branch analysis aka comparing branches through sonarqube is only available in the [deveoper edition](https://docs.sonarqube.org/latest/branches/overview/) of Sonarqube. But we could still have them analyzed independently.

we could write a script that does the following for frontend AND backend:

In the `sonar-project.properties` fills the `sonar.projectKey=ddueruem-web-frontend-${BRANCH_NAME}`, where `BRANCH_NAME` stands for the current branch.

This should then tell sonarqube to make a unique project per branch for frontend AND backend.

**Comment by Bishares** [comment]
The main part of this issue was figuring out how to write a readable value for the `sonar.projectKey` property into the `sonar-project.properties` file.

This is the working solution:
```YAML
- name: Set Sonarqube Project Name
      run: |
        sed -ir "s/^[#]*\s*sonar\.projectKey=.*/sonar\.projectKey=ddueruem\-web\-frontend\-$(echo "${{ github.ref_name }}" | sed -r 's/[\/]+/_/g' | sed -r 's/[-]+/\\\-/g')/" ${{ github.workspace }}/frontend/sonar-project.properties
```
### Explanation
This explanation is for the frontend `sonar-project.properties` file, the query works the same for the backend.
there is an **outer part** of the sed regex formula and an **inner part**.

**inner part**

`$(echo "${{ github.ref_name }}" | sed -r 's/[\/]+/_/g' | sed -r 's/[-]+/\\\-/g')` 

This will take the `ref_name` (which is the name of the current branch) and pipe it's name through two sed queries. The first query replaces all `/` symbols with `_` symbols. The second part replaces all `-` symbols with `\-` symbols (escaping needed for the outer sed query. The `$(echo result)` will basically evaluate the sed queryy and put the result into a string which can be used by the outer part.

**outer part**
(For this explanation the actual inner part is replaced with `$innerPart`)

`sed -ir "s/^[#]*\s*sonar\.projectKey=.*/sonar\.projectKey=ddueruem\-web\-frontend\-$innerPart/" ${{ github.workspace }}/frontend/sonar-project.properties`

This sed query will set all (also commented property values with the key `sonar.projectKey` to the value of `ddueruem-web-frontend-$innerPart`. The parameter `${{ github.workspace }}/frontend/sonar-project.properties` is the path to the properties file.
